图片:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .webp
文档:
  - .pdf
  - .docx
  - .doc
  - .txt
  - .xlsx
  - .xls
安装包:
  - .exe
  - .msi
  - .dmg
  - .pkg
压缩包:
  - .zip
  - .rar
  - .7z
  - .tar
视频:
  - .mp4
  - .avi
